# -*- coding: utf-8 -*-
"""A/B Testing for Themes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RJJ5Tw0iaH2iWKGkg-fVlSVWAFGGtQc
"""

import numpy as np

import pandas as pd

import plotly.express as px

import plotly.graph_objects as go

from statsmodels.stats.proportion import proportions_ztest

import matplotlib.pyplot as plt

from scipy import stats

data = pd.read_csv('/content/website_ab_test.csv')

data.head()

data.isnull().sum()

data.info()

data.describe()

data.shape

data.columns

"""Now before moving forward, here’s the detail of all the columns you should know:

Theme: dark or light

Click Through Rate: The proportion of the users who click on links or buttons on the website.

Conversion Rate: The percentage of users who signed up on the platform after visiting for the first time.

Bounce Rate: The percentage of users who leave the website without further interaction after visiting a single page.

Scroll Depth: The depth to which users scroll through the website pages.
Age: The age of the user.

Location: The location of the user.

Session Duration: The duration of the user’s session on the website.

Purchases: Whether the user purchased the book (Yes/No).

Added_to_Cart: Whether the user added books to the cart (Yes/No).
"""

fig = px.scatter(data,x='Click Through Rate',y='Conversion Rate',color='Theme',title='CTR vs Conversion Rate', trendline='ols')
fig.show()

light_theme_data = data[data['Theme'] == 'Light Theme']
dark_theme_data = data[data['Theme'] == 'Dark Theme']
fig = go.Figure()
fig.add_trace(go.Histogram(x=light_theme_data['Click Through Rate'], name='Light Theme', opacity=0.6))
fig.add_trace(go.Histogram(x=dark_theme_data['Click Through Rate'], name='Dark Theme', opacity=0.6))
fig.update_layout(
    title_text='Click Through Rate by Theme',
    xaxis_title_text='Click Through Rate',
    yaxis_title_text='Frequency',
    barmode='group',
    bargap=0.1
)
fig.show()

"""The relationship between the Click Through Rate (CTR) and Conversion Rate is consistent and nearly unchanged, as shown by the scatter plot. It means that as more users click on links or buttons (CTR increases), a similar proportion of them also end up signing up daily (Conversion Rate remains stable). In other words, the percentage of users who take the desired action of signing up remains roughly the same regardless of how many users initially clicked on links or buttons to explore the website.

"""

fig = go.Figure()

fig.add_trace(go.Histogram(x=light_theme_data['Conversion Rate'],
                           name='Light Theme', opacity=0.6, nbinsx=20))
fig.add_trace(go.Histogram(x=dark_theme_data['Conversion Rate'],
                           name='Dark Theme', opacity=0.6, nbinsx=20))

fig.update_layout(
    title_text='Conversion Rate by Theme',
    xaxis_title_text='Conversion Rate',
    yaxis_title_text='Frequency',
    barmode='group',
    bargap=0.1
)

fig.show()

"""We can see in the above histogram that there’s not much difference between the performance of both themes. Now let’s have a look at the histogram of the conversion rates of both themes:"""

fig = go.Figure()
fig.add_trace(go.Box(y=light_theme_data['Bounce Rate'],
                     name='Light Theme'))
fig.add_trace(go.Box(y=dark_theme_data['Bounce Rate'],
                     name='Dark Theme'))

fig.update_layout(
    title_text='Bounce Rate by Theme',
    yaxis_title_text='Bounce Rate',
)

fig.show()

"""There’s not much difference between the bounce rates of both themes still, the bounce rate of the light theme is slightly lower (which means it’s slightly better). Now let’s have a look at the scroll depth of both themes:"""

fig = go.Figure()
fig.add_trace(go.Box(y=light_theme_data['Scroll_Depth'],
                     name='Light Theme'))
fig.add_trace(go.Box(y=dark_theme_data['Scroll_Depth'],
                     name='Dark Theme'))

fig.update_layout(
    title_text='Scroll Depth by Theme',
    yaxis_title_text='Scroll Depth',
)

fig.show()

"""There’s not much difference, but the scroll depth of the light theme is slightly better."""